spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: bd6ba5ef97be7d15c0e2e3cd1b8e8950
            client-secret: f1gE21vqvejsSatjeGfxMxmzNNPraDfT
            scope: profile_nickname, profile_image, account_email, birthday
            redirect-uri: http://localhost:8080/login/oauth2/code/{registrationId}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

jwt:
  issuer: test
  secret-key: XtvCnK/2CRsblAWCjeh22VAyXGjszJLR4xVQJ8CNTVk=
  access-token:
    expire-length: 3600000
  refresh-token:
    expire-length: 3600000
