version: "3"

networks:
  backend:
    driver: bridge

services:
  web-server:
    image: zxcv9203/nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - backend
    depends_on:
      - checkmoi-1
      - checkmoi-2
  checkmoi-1:
    image: zxcv9203/checkmoi
    container_name: checkmoi-1
    restart: always
    expose:
      - "8080"
    volumes:
      - ./:/home/ubuntu
    environment:
      PROFILE: prod
    networks:
      - backend
  checkmoi-2:
    image: zxcv9203/checkmoi
    container_name: checkmoi-2
    restart: always
    expose:
      - "8080"
    volumes:
      - ./:/home/ubuntu
    environment:
      PROFILE: prod
    networks:
      - backend
