name: develop ci

on:
  pull_request:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Execute Gradle build
        run: ./gradlew copyTest build

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "테스트 커버리지 측정"
          min-coverage-overall: 60
          min-coverage-changed-files: 60



